services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true 
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true 
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3001:3001"