services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true 
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true 
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3001:3001"
    command: bash -c "sleep 7 && npm install && npx prisma migrate dev && npx prisma db seed && npm run dev"
    depends_on:
      - typescript_app_db
  typescript_app_db:
    container_name: typescript_app_db 
    image: mysql:8.3.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: typescript_app_db
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3308:3306
    volumes:
      - typescript_app_db_data:/var/lib/mysql
    restart: always
volumes:
  typescript_app_db_data: